language: go
go:
   - 1.5
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
sudo: required
dist: trusty
notifications:
    irc: "chat.freenode.net#gorepost-test"
before_install:
    - go get github.com/arachnist/dyncfg
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get github.com/go-playground/overalls
    - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - go test -race -v ./...
    - $HOME/gopath/bin/overalls -project=github.com/arachnist/dyncfg -covermode=count -debug
    - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
